// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"_template_/model"
	"_template_/registry"
	"_template_/uow"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewRegistry(conn *gorm.DB) registry.Registry {
	iUsers := model.NewUserRepository(conn)
	repository := model.NewRepository(iUsers)
	unitOfWork := uow.New(conn)
	registryRegistry := registry.New(repository, unitOfWork)
	return registryRegistry
}
